[package]
name = "viewer_ui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
egui.workspace = true
egui-wgpu.workspace = true
egui-winit.workspace = true
wgpu.workspace = true
winit.workspace = true
tracing.workspace = true
image.workspace = true
justjp2.workspace = true
jpeg2k.workspace = true

viewer_core = { path = "../viewer_core" }
